### ISSUE TITLE
Getting SSL error

### ISSUE THREAD

**Issue by alenpaulvarghese** [warp-plus/warpy#7]
I am getting ssl error while registering a new user

```
└──╼ $python3 -m warpy
 ====================== 
 WARP+ WireGuard Python 
 By Arian Amiramjadi    
 ====================== 

1. Register User
2. Show Users
3. Remove User
0. Exit Script

Please enter a number: 1
Please specify a username: sudobootstraper
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 352, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] internal error (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stark/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cloudflareclient.com', port=443): Max retries exceeded with url: /v0a884/reg (Caused by SSLError(SSLError(1, '[SSL] internal error (_ssl.c:1108)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/stark/.local/lib/python3.8/site-packages/warpy/__main__.py", line 210, in <module>
    main()
  File "/home/stark/.local/lib/python3.8/site-packages/warpy/__main__.py", line 189, in main
    register()
  File "/home/stark/.local/lib/python3.8/site-packages/warpy/__main__.py", line 166, in register
    reg = warp_plus.register(warp_plus.generate_key())
  File "/home/stark/.local/lib/python3.8/site-packages/warpy/main.py", line 56, in register
    req = session.post(url, headers=headers, json=data)
  File "/home/stark/.local/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/stark/.local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/stark/.local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/stark/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.cloudflareclient.com', port=443): Max retries exceeded with url: /v0a884/reg (Caused by SSLError(SSLError(1, '[SSL] internal error (_ssl.c:1108)')))

```

**Comment by Dragon-Born** [comment]
It seems you have trouble accessing the cloudflare servers.
Is this happened on your first use of the script? are you using the latest version? I suggest you install the latest version via git  `pip3 install git+https://github.com/Dragon-Born/warpy`
If the problem persists use a VPN before using the script.

**Comment by Dragon-Born** [comment]
I’m closing this issue for now because of inactivity.
